import React from 'react'

export default function NFNContent() {
  return (
    <div className="bg-slate-800 font-mono flex justify-center py-8">
    <div>
    <iframe width="375" height="666" src="https://www.youtube.com/embed/4KWyvypDy8E" title="Blue chip project requires blue chip leaders. #shorts #nft #community" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/kSrCezVc5aA" title="Web3 is the gateway to $$ Millionaire status! #shorts #crypto #fyp" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/3P2CR_tQyfg" title="A good team will take these simple steps BEFORE taking your money. #shorts #crypto #podcast" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/zPOuAHUWSIg" title="Sometimes you just have to forget about the world. #family #kids" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/Qp777NIfnzA" title="End your bad bad habits, make million$. #shorts #success #funny" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/9wYwLrYCPIw" title="Ca$h I’d dying. #money #fyp #finance" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/txTPt-rho_0" title="3 tips for successful trading. #shorts #trading #trendingshorts" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/txTPt-rho_0" title="3 tips for successful trading. #shorts #trading #trendingshorts" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/GL1j2R2_hHk" title="Bitcoin shut down?!  #crypto #bitcoin #shorts" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/OY8mNsITAfc" title="URGENT BITCOIN UPDATE?!  #bitcoin #shorts #crypto" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/76TIUTATrWk" title="Next 100x altcoin gem?!  #shorts #crypto #sustainability" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/VD109IiaIJQ" title="Galactic Metaverse on Vechain!  #shorts #crypto #nft" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="380" height="675" src="https://www.youtube.com/embed/GFQv7CY-n-I" title="Marital counseling #crypto style." frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/pC4CSg1Yqig" title="Check yourself before you wreck yourself!" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/D3EtjrAyt38" title="So easy a caveman could do it! #crypto #nft" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="353" height="627" src="https://www.youtube.com/embed/cqiSj1MndqU" title="It’s a good day for a brand new logo!" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="380" height="675" src="https://www.youtube.com/embed/og4YDY-UYo4" title="Crypto paid my way!" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="401" height="713" src="https://www.youtube.com/embed/D3EtjrAyt38" title="So easy a caveman could do it! #crypto #nft" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="401" height="713" src="https://www.youtube.com/embed/wm3Fm7QS1LI" title="But we’ve never even met before!!!" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="401" height="713" src="https://www.youtube.com/embed/cqiSj1MndqU" title="It’s a good day for a brand new logo!" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="401" height="713" src="https://www.youtube.com/embed/n60fP2vpgAA" title="Bear market returns of 25%?!  What happens in the bull?  #crypto" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="401" height="713" src="https://www.youtube.com/embed/Q0gPOuaNGXg" title="Authors and readers-web3 has a place for you!  #web3 #crypto" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="401" height="713" src="https://www.youtube.com/embed/MXpnA0nIfWE" title="Altcoin gem on Vechain with MASSIVE potential!! #nft #crypto #shorts" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="401" height="713" src="https://www.youtube.com/embed/IddtzhdLwqA" title="All your #nft podcast needs, even my 7 year old gets it! #shorts" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
    </div>
  )
}
